src/Entity/Admin.php
<?php

namespace App\Entity;

use App\Repository\AdminRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass=AdminRepository::class)
 */
class Admin implements UserInterface, PasswordAuthenticatedUserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $username;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $email;

    
    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * @deprecated since Symfony 5.3, use getUserIdentifier instead
     */
    public function getUsername(): string
    {
        return (string) $this->username;
    }

    public function setUsername(string $username): self
    {
        $this->username = $username;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->username;
    }

    public function __toString(): string
    {
        return $this->username;
    }
    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

}

src/Entity/Fecha.php
<?php

namespace App\Entity;

use App\Repository\FechaRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=FechaRepository::class)
 */
class Fecha
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="date")
     */
    private $date_trayecto;

    /**
     * @ORM\Column(type="time")
     */
    private $time_at;

    /**
     * @ORM\Column(type="time")
     */
    private $time_to;

    /**
     * @ORM\ManyToOne(targetEntity=Grupo::class, inversedBy="fecha")
     * @ORM\JoinColumn(nullable=false)
     */
    private $grupo;

    /**
     * @ORM\OneToMany(targetEntity=Trayecto::class, mappedBy="fecha", orphanRemoval=true)
     */
    private $trayectos;


    public function __construct()
    {
        $this->trayectos = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDateTrayecto(): ?\DateTimeInterface
    {
        return $this->date_trayecto;
    }

    public function setDateTrayecto(\DateTimeInterface $date_trayecto): self
    {
        $this->date_trayecto = $date_trayecto;

        return $this;
    }

    public function getTimeAt(): ?\DateTimeInterface
    {
        return $this->time_at;
    }

    public function setTimeAt(\DateTimeInterface $time_at): self
    {
        $this->time_at = $time_at;

        return $this;
    }

    public function getTimeTo(): ?\DateTimeInterface
    {
        return $this->time_to;
    }

    public function setTimeTo(\DateTimeInterface $time_to): self
    {
        $this->time_to = $time_to;

        return $this;
    }

    /**
     * @return Collection<int, Trayecto>
     */
    public function getTrayectos(): Collection
    {
        return $this->trayectos;
    }

    public function addTrayecto(Trayecto $trayecto): self
    {
        if (!$this->trayectos->contains($trayecto)) {
            $this->trayectos[] = $trayecto;
            $trayecto->setFecha($this);
        }

        return $this;
    }

    public function removeTrayecto(Trayecto $trayecto): self
    {
        if ($this->trayectos->removeElement($trayecto)) {
            // set the owning side to null (unless already changed)
            if ($trayecto->getFecha() === $this) {
                $trayecto->setFecha(null);
            }
        }

        return $this;
    }

    public function getGrupo(): ?Grupo
    {
        return $this->grupo;
    }

    public function setGrupo(?Grupo $grupo): self
    {
        $this->grupo = $grupo;

        return $this;
    }
}

templates/index/newtime.html.twig
{% extends 'base.html.twig' %}

{% block title %}ComparteCoche{% endblock %}

{% block body %}
<section class="section">
    <div class="container">
        <h1 class="title">
            Nuevo Horario
        </h1>
        <p class="subtitle">
            Añada un nuevo horario a su historial
        </p>
    </div>
</section>

<div class="container is-fluid">
    {{ form_errors(form)}}
    {{ form_start(form) }}
    <div class="field">
        <label class="label">Fecha</label>
        <div class="control has-icons-left">            
            {{ form_widget(form.date_trayecto, {'attr': {'class': 'input is-success'}}) }}
            <span class="icon is-small is-left">
                <i id="emailCheckIconLeft" class="fas fa-calendar-alt"></i>
            </span>
        </div>
    </div>
    <div class="columns">
        <div class="column is-one-quarter">
            <div class="field">
                <label class="label">Inicio</label>
                <div class="control has-icons-left">            
                    {{ form_widget(form.time_at, {'attr': {'class': 'input is-success'}}) }}            
                    <span class="icon is-small is-left">
                        <i id="emailCheckIconLeft" class="fas fa-clock"></i>
                    </span>
                </div>
            </div>
        </div>
        <div class="column is-one-quarter">
            <div class="field">
                <label class="label">Fin</label>
                <div class="control has-icons-left">            
                    {{ form_widget(form.time_to, {'attr': {'class': 'input is-success'}}) }}            
                    <span class="icon is-small is-left">
                        <i id="emailCheckIconLeft" class="fas fa-clock"></i>
                    </span>
                </div>
            </div>
        </div>
    </div>
    <!--Submit button-->
    <div class="field is-grouped">
        <div class="control">
            {{ form_widget(form.submit, {'attr': {'class': 'button is-link', 'name': 'Enviar'}}) }}
        </div>
    </div>
    {{ form_end(form) }}
</div>                        

{% endblock %}

templates/index/passenger_accept.html.twig
{% extends 'base.html.twig' %}

{% block title %}ComparteCoche{% endblock %}
{% block stylesheets %}
    <!-- Bootstrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <!-- Icons -->
    <link href="/fonts/font-awesome/css/font-awesome.css" rel="stylesheet">
{% endblock %}

{% block body %}
    <section class="container px-4 mt-5 mb-5">
        <div class="row gx-5">
            {% if app.user %}            
                <div class="container overflow-hidden">
                    <div class="row gx-5">
                        <div class="col mb-1">
                            <div class="p-3 border bg-warning bg-gradient">{{ app.user.userIdentifier }}</div>
                        </div>
                        <div class="col mb-1">
                            <div class="p-3 border text-white bg-secondary bg-gradient">{{ grupo }}</div>
                        </div>
                    </div>
                </div>

                <div class="container-lg">
                    <div class="container-sm">
                        <h3>Trayecto Creado</h3>
                        <div class="container px-4">
                            <div class="d-flex flex-column mb-3">
                                <div class="d-flex justify-content-center">
                                    <div class="d-flex justify-content-evenly container-sm p-3 border bg-light">
                                        
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>    
                </div><!-- container -->
            {% endif %}
        </div>
    </section>
{% endblock %}

templates/index/trayecto.html.twig
{% extends 'base.html.twig' %}

{% block title %}ComparteCoche{% endblock %}

{% block body %}

<section class="section">
    <div class="container">
        <h1 class="title">
            Trayecto
        </h1>
        <p class="subtitle">
            Viaje disponible
        </p>
    </div>
</section>

<div class="container is-fluid">
    <article class="tile is-child notification is-success">
        <p class="title">Opciones</p>
        <p class="subtitle">Elija alguna de las opciones disponibles</p>
        <div class="content">
            {% if estoy %}
                <div class="buttons">
                    <button class="button is-danger" onclick="location.href='{{ path('app_delTrayecto', {id: otros[0].id}) }}'">Me borro!!</button>
                    {% if otros|length > 1 %}
                        <button class="button is-link" onclick="location.href='{{ path('app_pongocoche', {id: otros[0].id}) }}'">Yo conduzco</button>
                    {% endif %}
                </div>
            {% else %}
                <div class="buttons">
                    <button class="button is-link" onclick="location.href='{{ path('app_addTrayecto', {id: otros[0].id}) }}'">Me apunto!!</button>
                </div>
            {% endif %}
        </div>
    </article>
</div>

<div class="container is-fluid mt-2">
    <article class="tile is-child notification is-warning">
        <nav class="level px-3 py-2">
            <div class="level-left">
                <div class="level-item">
                    <div class="control">
                    <span class="tag is-large is-link">
                        {{ otros[0].fecha.dateTrayecto | format_datetime('short', 'none', locale='fr') }}                
                    </span>
                    <span class="tag is-danger">
                        {{ otros[0].fecha.timeAt | format_time(pattern='HH:mm') }}
                    </span>
                    <span class="tag is-danger">
                        {{ otros[0].fecha.timeTo | format_time(pattern='HH:mm') }}
                    </span>
                    </div>
                </div>
                {% if estoy %}                    
                    {% for key, grupos in mayoria %}
                        <div class="level-item">
                            <span class="tag is-link">Con {{ key }} Puntos:</span>
                        </div>
                        <div class="level-item">
                            <div class="avatars">
                            {% for usuario in grupos %}
                                <div class="avatar">
                                    <img src="/images/avatars/{{ usuario.avatar }}" alt="{{ usuario.username }}" onclick='location.href = "{{ path('app_user', {id: usuario.id}) }}"'>
                                    {% if usuario.username != '' %}
                                        <span class="tooltiptext">{{ usuario.username }}</span>                                        
                                    {% else %}
                                        <span class="tooltiptext">{{ usuario.email }}</span>
                                    {% endif %}
                                    
                                </div>                                
                            {% endfor %}
                            </div>
                        </div>
                    {% endfor %}                                 
                {% else %}
                    <div class="level-item">                    
                        <div class="avatars">
                        {% for track in otros %}                            
                            {% if track.driver.avatar %}
                                <div class="avatar">
                                    <img src="/images/avatars/{{ track.driver.avatar }}" alt="{{ track.driver.email }}" onclick='location.href = "{{ path('app_user', {id: track.driver.id}) }}"'>
                                    {% if track.driver.username != '' %}
                                        <span class="tooltiptext">{{ track.driver.username }}</span>                                        
                                    {% else %}
                                        <span class="tooltiptext">{{ track.driver.email }}</span>
                                    {% endif %}
                                </div>
                            {% else %}
                                <img src="/images/avatars/default.png" alt="{{ track.driver.email }}">
                                {% if track.driver.username != '' %}
                                    <span class="tooltiptext">{{ track.driver.username }}</span>                                        
                                {% else %}
                                    <span class="tooltiptext">{{ track.driver.email }}</span>
                                {% endif %}
                            {% endif %}                        
                        {% endfor %}
                        </div>
                    </div>
                {% endif %}
            </div>
        </nav>
    </article>
</div>


                            
{% endblock %}

templates/index/trayecto_end.html.twig
{% extends 'base.html.twig' %}

{% block title %}ComparteCoche{% endblock %}

{% block body %}

<section class="section">
    <div class="container">
        <h1 class="title">
            Trayecto
        </h1>
        <p class="subtitle">
            Viaje Cerrado
        </p>
    </div>
</section>

<div class="container is-fluid">
    <article class="tile is-child notification is-success">
        <p class="title">Opciones</p>
        <p class="subtitle">Elija alguna de las opciones disponibles</p>
        <div class="content">            
            <div class="buttons">
                
                {% set existe = false  %}
                {% for track in otros %}                                        
                    {#{dump(track.driver.id)}#}
                    {% if app.user.id == track.driver.id and track.passenger == false %}
                        {% set existe = true  %}
                    {% endif %}
                {% endfor %}
                {% if estoy %}
                    <button class="button is-danger" onclick="location.href='{{ path('app_delTrayecto', {id: otros[0].id}) }}'">Me borro!!</button>
                    {% if existe %}
                        <button class="button is-warning" onclick="location.href='{{ path('app_confirm_trayecto', {id: otros[0].id}) }}'">Confirmar</button>
                    {% endif %}                    
                {% else %}
                    <button class="button is-link" onclick="location.href='{{ path('app_addTrayecto', {id: otros[0].id}) }}'">Me apunto!!</button
                {% endif %}
            </div>
        </div>
    </article>
</div>

<div class="container is-fluid mt-2">
    <article class="tile is-child notification is-danger">
        <nav class="level px-3 py-2">
            <div class="level-left">
                <div class="level-item">
                    <div class="control">
                    <span class="tag is-large is-link">
                        {{ otros[0].fecha.dateTrayecto | format_datetime('short', 'none', locale='fr') }}                
                    </span>
                    <span class="tag is-warning">
                        {{ otros[0].fecha.timeAt | format_time(pattern='HH:mm') }}
                    </span>
                    <span class="tag is-warning">
                        {{ otros[0].fecha.timeTo | format_time(pattern='HH:mm') }}
                    </span>
                    </div>
                </div>
                
                <div class="level-item">                    
                    <div class="avatars">
                    {% for track in otros %}
                        
                        {% if track.passenger %}
                            <span class="icon has-text-success rounded passenger">
                                <i class="fas fa-user"></i>
                            </span>
                        {% else %}
                            <span class="icon has-text-warning rounded car">
                                <i class="fas fa-car"></i>
                            </span>
                        {% endif %}
                        <div class="avatar">
                            {% if track.driver.avatar %}                            
                                <img src="/images/avatars/{{ track.driver.avatar }}" alt="{{ track.driver.email }}" onclick='location.href = "{{ path('app_user', {id: track.driver.id}) }}"'>
                            {% else %}
                                <img src="/images/avatars/default.png" alt="{{ track.driver.email }}">
                            {% endif %}
                            {% if track.driver.username != '' %}
                                <span class="tooltiptext">{{ track.driver.username }}</span>                                        
                            {% else %}
                                <span class="tooltiptext">{{ track.driver.email }}</span>
                            {% endif %}                            
                        </div>
                    {% endfor %}
                    </div>
                </div>            
            
        </nav>
    </article>
</div>


                            
{% endblock %}

templates/index/viewlog.html.twig
{% extends 'base.html.twig' %}

{% block title %}ComparteCoche :: Registro{% endblock %}

{% block body %}
<section class="section">
    <div class="container">
        <h1 class="title">
            Registro de eventos
        </h1>
        <p class="subtitle">
            Log
        </p>
    </div>
</section>
<!-- https://core.telegram.org/widgets/post -->
<div class="container is-fluid">
    <script async src="https://telegram.org/js/telegram-widget.js?19" data-telegram-post="malpagaos/2" data-width="100%"></script>
    <script async src="https://telegram.org/js/telegram-widget.js?19" data-telegram-post="malpagaos/3" data-width="100%"></script>
    <script async src="https://telegram.org/js/telegram-widget.js?19" data-telegram-post="malpagaos/4" data-width="100%"></script>
</div>                        

{% endblock %}